services:
  postgres:
    container_name: sheepai-postgres
    image: "postgres:18"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sheepai
      POSTGRES_PASSWORD: sheepai
      POSTGRES_DB: sheepai
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
